# Generated by Django 5.0.3 on 2024-03-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('position', models.TextField()),
                ('standard', models.CharField(max_length=255)),
                ('message_type', models.IntegerField(null=True)),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.verdict')),
            ],
        ),
    ]
